apiVersion: v1
kind: page
spec:
  id: gIr39w1
  title: githubUsers
  display: shell
  content:
    - component: PageRow
      name: pageRow4
      children:
        - component: Text
          name: text1
          props:
            value: npm users
            variant: h4
    - component: PageRow
      name: pageRow6
      children:
        - component: Text
          name: text3
          props:
            mode: markdown
            value: >
              Token to renew in
              https://www.npmjs.com/settings/oliviertassinari/tokens/
    - component: PageRow
      name: pageRow2
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                listUser.data
            height: 310
            columns:
              - field: name
                type: string
                width: 156
              - field: role
                type: string
    - component: PageRow
      name: pageRow3
      children:
        - component: Text
          name: text
          props:
            value: Invite new user
            variant: h4
    - component: PageRow
      name: pageRow
      children:
        - component: TextField
          name: slug
          props:
            fullWidth: false
            label: new user npm slug
            sx:
              width: 300
    - component: PageRow
      name: pageRow1
      children:
        - component: Button
          name: button
          props:
            loading:
              $$jsExpression: |
                inviteUser.isLoading
            content: Invite
            onClick:
              $$jsExpressionAction: |-
                inviteUser.call({
                  slug: slug.value
                })
            disabled:
              $$jsExpression: |
                slug.value === ""
            fullWidth: false
    - component: PageRow
      name: pageRow5
      children:
        - component: Text
          name: text2
          props:
            mode: markdown
            value:
              $$jsExpression: |
                `response:

                \`\`\`json
                ${JSON.stringify(inviteUser.data, null, 2)}
                \`\`\`
                `
            loading: false
