apiVersion: v1
kind: page
spec:
  id: gIr39w1
  title: githubUsers
  display: shell
  content:
    - component: PageRow
      name: pageRow4
      children:
        - component: Text
          name: text1
          props:
            value: GitHub users
            variant: h4
    - component: PageRow
      name: pageRow2
      children:
        - component: DataGrid
          name: dataGrid
          props:
            rows:
              $$jsExpression: |
                listUser.data
            height: 324
            columns:
              - field: login
                type: string
                width: 177
              - field: type
                type: string
              - field: site_admin
                type: boolean
    - component: PageRow
      name: pageRow3
      children:
        - component: Text
          name: text
          props:
            value: Invite new user
            variant: h4
    - component: PageRow
      name: pageRow
      children:
        - component: TextField
          name: username
          props:
            fullWidth: false
            label: new user GitHub username
            sx:
              width: 300
    - component: PageRow
      name: pageRow1
      children:
        - component: Button
          name: button
          props:
            fullWidth: false
            loading:
              $$jsExpression: |
                inviteUser.isLoading
            content: Invite
            onClick:
              $$jsExpressionAction: inviteUser.call()
            disabled:
              $$jsExpression: |
                username.value === ""
    - component: PageRow
      name: pageRow5
      children:
        - component: Text
          name: text2
          props:
            loading: false
            mode: markdown
            value:
              $$jsExpression: |
                `response:

                \`\`\`json
                ${JSON.stringify(inviteUser.data, null, 2)}
                \`\`\`
                `
  queries:
    - name: inviteUser
      mode: mutation
      query:
        function: githubInviteUser
        kind: local
      parameters:
        - name: username
          value:
            $$jsExpression: |
              username.value
    - name: listUser
      query:
        function: githubListUsers
        kind: local
